"<Nordisk>"
	"nordisk" adj sint pst ut sg ind
	"nordisk" adj sint pst nt sg ind
	"nordisk" adj sint pst un sg ind
"<før>"
	"før" pr SELECT:4074:2639
;	"før" adv REMOVE:1586:3608
;	"føre" vblex imp REMOVE:6524:2114
;	"før" n nt sg ind nom SELECT:4074:2639
;	"før" cnjsub SELECT:4074:2639
;	"før" cnjadv SELECT:4074:2639
-
"<kristen>"
	"kristen" adj sint pst ut sg ind
"<begravelse>"
	"begravelse" n ut sg ind nom
"<dækker>"
	"dække" vblex pres actv SELECT:5348:2462
;	"dække" n ut pl ind nom SELECT:5348:2462
;	"dække" n nt pl ind nom SELECT:5348:2462
"<over>"
	"over" pr
"<flere>"
	"flere" det qnt un pl SELECT:3641:2783
;	"mange" adj sint comp un sp SELECT:3641:2783
"<forskellige>"
	"forskellig" adj sint pst un pl ind SELECT:2483:3057
;	"forskellige" adv SELECT:2483:3057
;	"forskellig" adj sint pst un sp def SELECT:2483:3057
"<former>"
	"form" n ut pl ind nom SELECT:4813:2560
	"forme" n ut pl ind nom SELECT:4813:2560
;	"forme" vblex pres actv SELECT:4813:2560
;	"formere" vblex imp SELECT:4813:2560
;	"former" n ut sg ind nom SELECT:4813:2560
"<for>"
	"for" pr SELECT:4213:2651
;	"for" adv REMOVE:1573:3631
;	"fore" vblex imp REMOVE:1578:3626
;	"fare" vblex past actv REMOVE:1578:3626
;	"for" n nt pl ind nom REMOVE:1728:10011
;	"for" n nt sg ind nom REMOVE:1728:10011
;	"fare" adj pp nt sg ind SELECT:4213:2651
;	"for" cnjsub SELECT:4213:2651
;	"fare" adj pp ut sg ind SELECT:4213:2651
"<begravelsestraditioner>"
	"begravelse" n ut sg ind nom cmp
		"tradition" n ut pl ind nom
"<,>"
	"," cm
	"," cm clb
"<der>"
	"der" adv SELECT:3365:2848
;	"der" pr SELECT:3365:2848
;	"der" cnjsub SELECT:3365:2848
;	"der" prn rel un sp nom SELECT:3365:2848
"<blev>"
	"blive" vblex past actv
"<praktiseret>"
	"praktisere" vblex pp SELECT:5664:2406
;	"praktisere" adj pp ut sg ind SELECT:5664:2406
;	"praktisere" adj pp nt sg ind SELECT:5664:2406
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<Norden>"
	"nord" n ut sg def nom
;	"norden" n ut sg ind nom REMOVE:6968:2033
;	"norden" n nt sg ind nom REMOVE:6968:2033
"<før>"
	"før" pr SELECT:4213:2651
;	"før" adv REMOVE:1586:3608
;	"før" n nt sg ind nom SELECT:4213:2651
;	"før" cnjsub SELECT:4213:2651
;	"før" cnjadv SELECT:4213:2651
;	"føre" vblex imp SELECT:4213:2651
"<religionsskiftet>"
	"religion" n ut sg ind nom cmp
		"skift" n nt sg def nom
	"religion" n ut sg ind nom cmp
		"skifte" n nt sg def nom
"<,>"
	"," cm
	"," cm clb
"<dvs.>"
	"dvs." abbr
	"dvs." n nom
"<fra>"
	"fra" pr SELECT:4112:2642
;	"fra" adv SELECT:4112:2642
;	"fra" cnjadv SELECT:4112:2642
;	"fra" abbr SELECT:4112:2642
"<ca.>"
	"ca." adv
	"ca." abbr
	"ca." n nom
"<7.000>"
	"7.000" det qnt pl
"<f>"
	"falphabet" n nt sg ind nom
"<.>"
	"." sent

"<Kr.>"
	"kr." abbr
	"kr." n nom
"<til>"
	"til" pr SELECT:1436:3184
;	"til" adv SELECT:1436:3184
;	"til" cnjsub SELECT:1436:3184
;	"til" cnjadv SELECT:1436:3184
"<ca.>"
	"ca." adv
	"ca." abbr
	"ca." n nom
"<1.000>"
	"1.000" det qnt pl
"<e.Kr.>"
	"e.Kr." abbr
"<Betegnelsen>"
	"betegnelse" n ut sg def nom
"<dækker>"
	"dække" vblex pres actv SELECT:5348:2462
;	"dække" n ut pl ind nom SELECT:5348:2462
;	"dække" n nt pl ind nom SELECT:5348:2462
"<over>"
	"over" pr
"<mange>"
	"mange" det qnt un pl SELECT:3641:2783
;	"mange" prn ind un pl nom SELECT:3641:2783
;	"mange" adj sint pst un pl ind SELECT:3641:2783
"<forskellige>"
	"forskellig" adj sint pst un pl ind SELECT:2483:3057
;	"forskellige" adv SELECT:2483:3057
;	"forskellig" adj sint pst un sp def SELECT:2483:3057
"<skikke>"
	"skik" n ut pl ind nom
"<,>"
	"," cm
	"," cm clb
"<da>"
	"da" cnjsub SELECT:4672:2570
;	"da" adv SELECT:4672:2570
;	"da" cnjadv SELECT:4672:2570
"<gravlægninger>"
	"*gravlægninger"
"<varierede>"
	"variere" vblex past actv
;	"variere" adj pp pl REMOVE:7682:1895
;	"variere" adj pp sg def REMOVE:7682:1895
"<efter>"
	"efter" pr SELECT:4112:2642
;	"efter" cnjadv SELECT:4112:2642
"<tid>"
	"tid" n ut sg ind nom
"<og>"
	"og" adv
	"og" cnjcoo
"<sted>"
	"sted" adv
	"sted" n nt sg ind nom
"<..>"
	".." sent


"<Kilderne>"
	"kilde" n ut pl def nom
"<viser>"
	"vise" vblex pres actv
;	"vise" n ut pl ind nom REMOVE:7138:1981
"<fællestræk>"
	"fællestræk" n nt sg ind nom
	"fællestræk" n nt pl ind nom
"<og>"
	"og" adv
	"og" cnjcoo
"<variationer>"
	"variation" n ut pl ind nom
"<for>"
	"fare" adj pp ut sg ind
	"for" pr
	"for" cnjsub
;	"for" adv REMOVE:1573:3631
;	"fore" vblex imp REMOVE:1578:3626
;	"fare" vblex past actv REMOVE:1578:3626
;	"for" n nt pl ind nom REMOVE:1728:10011
;	"for" n nt sg ind nom REMOVE:1728:10011
;	"fare" adj pp nt sg ind REMOVE:6037:2291
"<begravelsesformerne>"
	"begravelse" n ut sg ind nom cmp
		"form" n ut pl def nom
	"begravelse" n ut sg ind nom cmp
		"forme" n ut pl def nom
	"begravelse" n ut sg ind nom cmp
		"former" n ut pl def nom
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<Norden>"
	"nord" n ut sg def nom
;	"norden" n ut sg ind nom REMOVE:6968:2033
;	"norden" n nt sg ind nom REMOVE:6968:2033
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1481:10004
"<før>"
	"før" pr SELECT:4239:2653
;	"før" adv REMOVE:1586:3608
;	"før" n nt sg ind nom SELECT:4239:2653
;	"før" cnjsub SELECT:4239:2653
;	"før" cnjadv SELECT:4239:2653
;	"føre" vblex imp SELECT:4239:2653
-
"<kristen>"
	"kristen" adj sint pst ut sg ind
"<tid>"
	"tid" n ut sg ind nom
"<.>"
	"." sent

"<Det>"
	"den" det dem nt sg
	"det" prn p3 nt sg nom
	"det" prn p3 nt sg acc
"<mest>"
	"mest" preadv
	"meget" adj sint sup un sp ind
"<omfattende>"
	"omfatte" adj pprs
	"omfattende" adj sint pst ut sg ind
	"omfattende" adj sint pst nt sg ind
	"omfattende" adj sint pst un sp def
;	"omfattende" adj sint pst un pl ind REMOVE:6001:2299
"<kildemateriale>"
	"kildemateriale" n nt sg ind nom
"<er>"
	"være" vbser pres actv
"<arkæologiske>"
	"arkæologisk" adj sint pst un pl ind SELECT:2373:3050
;	"arkæologisk" adj sint pst un sp def SELECT:2373:3050
"<udgravninger>"
	"udgravning" n ut pl ind nom
"<og>"
	"og" adv
	"og" cnjcoo
"<ganske>"
	"ganske" adv
"<få>"
	"få" adj sint pst nt sg ind SELECT:2808:2974
;	"få" vblex imp REMOVE:6524:2114
;	"få" vblex inf actv REMOVE:7479:1909
;	"få" adj sint pst un sp def SELECT:2808:2974
;	"få" adj sint pst un pl ind SELECT:2808:2974
;	"få" adj sint pst ut sg ind SELECT:2808:2974
"<samtidige>"
	"samtidig" adj sint pst un pl ind SELECT:2425:3054
;	"samtidig" adj sint pst un sp def SELECT:2425:3054
"<og>"
	"og" adv
	"og" cnjcoo
"<yngre>"
	"ung" adj sint comp un sp
"<skriftlige>"
	"skriftlig" adj sint pst un pl ind SELECT:2425:3054
;	"skriftlig" adj sint pst un sp def SELECT:2425:3054
"<kilder>"
	"kilde" n ut pl ind nom SELECT:4813:2560
;	"kilde" vblex pres actv SELECT:4813:2560
"<,>"
	"," cm
	"," cm clb
"<der>"
	"der" adv SELECT:3365:2848
;	"der" pr SELECT:3365:2848
;	"der" cnjsub SELECT:3365:2848
;	"der" prn rel un sp nom SELECT:3365:2848
"<beskriver>"
	"beskrive" vblex pres actv
"<ritualer>"
	"ritual" n nt pl ind nom
"<og>"
	"og" adv
	"og" cnjcoo
"<forløbet>"
	"forløb" n nt sg def nom
"<af>"
	"af" pr
"<vikingetidens>"
	"*vikingetidens"
"<begravelser>"
	"begravelse" n ut pl ind nom
"<.>"
	"." sent

"<En>"
	"en" det ind ut sg
	"en" num sg ut
;	"ene" vblex imp REMOVE:6524:2114
;	"en" det qnt ut sg REMOVE:8533:10028
"<af>"
	"af" pr
"<de>"
	"den" det dem un pl SELECT:3641:2783
;	"de" np al sg nom SELECT:3641:2783
;	"de" prn p3 un pl nom SELECT:3641:2783
"<mest>"
	"mest" preadv
	"meget" adj sint sup un sp ind
"<berømte>"
	"berømt" adj sint pst un pl ind SELECT:2483:3057
;	"berømt" adj sint pst un sp def SELECT:2483:3057
"<beskrivelser>"
	"beskrivelse" n ut pl ind nom
"<er>"
	"være" vbser pres actv
"<den>"
	"den" det dem ut sg
	"den" prn p3 ut sg nom
;	"den" prn p3 ut sg acc REMOVE:6744:2055
"<arabiske>"
	"arabisk" adj sint pst un sg def
	"arabisk" adj sint pst un sp def
;	"arabisk" adj sint pst un pl ind REMOVE:6001:2299
"<diplomat>"
	"diplomat" n ut sg ind nom
"<Ibn>"
	"Ibn" np ant m nom
"<Fadlans>"
	"*Fadlans"
"<skildring>"
	"skildring" n ut sg ind nom
"<af>"
	"af" pr
"<en>"
	"en" det ind ut sg
;	"en" num sg ut REMOVE:1694:10025
;	"ene" vblex imp REMOVE:6524:2114
;	"en" det qnt ut sg REMOVE:8533:10028
"<høvdingebegravelse>"
	"*høvdingebegravelse"
"<ved>"
	"ved" pr SELECT:4112:2642
;	"vide" vblex pres actv REMOVE:8643:4039
;	"ved" adv SELECT:4112:2642
"<Volga>"
	"Volga" np top nom
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<Rusland>"
	"rusland" np top nom
"<..>"
	".." sent


"<De>"
	"de" prn p3 un pl nom
	"De" prn p2 un pl nom
	"den" det dem un pl
;	"de" np al sg nom REMOVE:7835:de-np
"<døde>"
	"død" adj sint pst un pl ind
	"dø" adj pp pl
	"død" adj sint pst un sp def
	"død" n ut pl ind nom
;	"dø" adj pp sg def REMOVE:5875:2307
;	"dø" vblex past actv REMOVE:7783:1831
"<fik>"
	"få" vblex past actv
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<reglen>"
	"regel" n ut sg def nom
	"regle" n ut sg def nom
"<personlige>"
	"personlig" adj sint pst un pl ind
	"personlig" adj sint pst un sp def
"<ejendele>"
	"*ejendele"
"<med>"
	"med" adv
	"med" pr
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<graven>"
	"grav" n ut sg def nom
	"grave" n ut sg def nom
"<som>"
	"som" cnjsub
	"som" prn rel un sp nom
"<gravgaver>"
	"grav" n ut sg ind nom cmp
		"gav" n ut pl ind nom
	"grav" n ut sg ind nom cmp
		"gave" n ut pl ind nom
"<.>"
	"." sent

"<De>"
	"De" prn p2 un pl nom SELECT:4434:2607
	"de" prn p3 un pl nom SELECT:4434:2607
;	"de" np al sg nom SELECT:4434:2607
;	"den" det dem un pl SELECT:4434:2607
"<afspejler>"
	"afspejle" vblex pres actv
"<deres>"
	"den" det pos un pl
	"de" prn pos p3 un pl
	"deres" det pos un sp
"<sociale>"
	"social" adj sint pst un sp def
;	"social" adj sint pst un pl ind REMOVE:6001:2299
"<status>"
	"status" n ut sg ind nom
"<.>"
	"." sent

"<Graven>"
	"Graven" np cog nom
	"grav" n ut sg def nom
	"grave" n ut sg def nom
"<kunne>"
	"kunne" vbmod inf actv
	"kunne" vbmod past actv
"<være>"
	"være" vbser inf actv
"<dækket>"
	"dække" vblex pp SELECT:5782:2410
;	"dæk" n nt sg def nom SELECT:5782:2410
;	"dække" adj pp ut sg ind SELECT:5782:2410
;	"dække" adj pp nt sg ind SELECT:5782:2410
;	"dække" n nt sg def nom SELECT:5782:2410
"<af>"
	"af" pr
"<en>"
	"en" det ind ut sg
;	"en" num sg ut REMOVE:1694:10025
;	"ene" vblex imp REMOVE:6544:2117
;	"en" det qnt ut sg REMOVE:8533:10028
"<gravhøj>"
	"gravhøj" n ut sg ind nom
"<eller>"
	"eller" cnjcoo
	"el" n ut pl ind nom
"<markeret>"
	"markere" vblex pp
	"markere" adj pp ut sg ind
	"markere" adj pp nt sg ind
	"markeret" adj sint pst ut sg ind
	"markeret" adj sint pst nt sg ind
"<med>"
	"med" pr SELECT:4112:2642
;	"med" adv SELECT:4112:2642
"<sten>"
	"sten" adv
	"sten" adj sint pst un sp def
	"sten" n ut sg ind nom
	"sten" n ut pl ind nom
	"sten" adj sint pst ut sg ind
	"sten" adj sint pst nt sg ind
	"sten" adj sint pst un pl ind
;	"stene" vblex imp REMOVE:6544:2117
"<.>"
	"." sent

"<I>"
	"i" pr SELECT:1183:10005
;	"I" np top nom SELECT:1183:10005
;	"I" prn p2 un pl nom SELECT:1183:10005
;	"ialphabet" n nt sg ind nom SELECT:1183:10005
"<de>"
	"den" det dem un pl SELECT:3641:2783
;	"de" np al sg nom SELECT:3641:2783
;	"de" prn p3 un pl nom SELECT:3641:2783
"<sidste>"
	"sidst" adj sint pst un pl ind SELECT:2483:3057
;	"sidst" adj sint pst un sp def SELECT:2483:3057
;	"sidst" adj sint sup un sp ind SELECT:2483:3057
;	"sidst" adj sint sup un sp def SELECT:2483:3057
"<århundreder>"
	"århundrede" n nt pl ind nom
"<før>"
	"før" pr SELECT:4074:2639
;	"før" adv REMOVE:1586:3608
;	"føre" vblex imp REMOVE:6524:2114
;	"før" n nt sg ind nom SELECT:4074:2639
;	"før" cnjsub SELECT:4074:2639
;	"før" cnjadv SELECT:4074:2639
"<religionsskiftet>"
	"religion" n ut sg ind nom cmp
		"skift" n nt sg def nom
	"religion" n ut sg ind nom cmp
		"skifte" n nt sg def nom
"<blev>"
	"blive" vblex past actv
"<runesten>"
	"runesten" n ut sg ind nom
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<mange>"
	"mange" det qnt un pl SELECT:3641:2783
;	"mange" prn ind un pl nom SELECT:3641:2783
;	"mange" adj sint pst un pl ind SELECT:3641:2783
"<tilfælde>"
	"tilfælde" n nt sg ind nom
	"tilfælde" n nt pl ind nom
"<brugt>"
	"bruge" vblex pp SELECT:5782:2410
;	"bruge" adj pp ut sg ind SELECT:5782:2410
;	"bruge" adj pp nt sg ind SELECT:5782:2410
"<som>"
	"som" cnjsub
;	"som" prn rel un sp nom REMOVE:6683:2073
"<mindesmærke>"
	"mindesmærke" n nt sg ind nom
"<for>"
	"for" adv SELECT:759:3652
;	"for" pr SELECT:759:3652
;	"for" cnjsub SELECT:759:3652
;	"fore" vblex imp SELECT:759:3652
;	"fare" vblex past actv SELECT:759:3652
;	"for" n nt sg ind nom SELECT:759:3652
;	"for" n nt pl ind nom SELECT:759:3652
;	"fare" adj pp ut sg ind SELECT:759:3652
;	"fare" adj pp nt sg ind SELECT:759:3652
"<afdøde>"
	"afdød" adj sint pst un pl ind
	"afdød" adj sint pst un sp def
"<,>"
	"," cm
	"," cm clb
"<men>"
	"men" cnjcoo SELECT:998:3443
;	"mene" vblex imp SELECT:998:3443
;	"men" n nt sg ind nom SELECT:998:3443
;	"men" n nt pl ind nom SELECT:998:3443
"<kun>"
	"kun" adv
;	"kunne" vbmod imp REMOVE:6529:2115
"<sjældent>"
	"sjælden" adj sint pst nt sg ind
"<brugt>"
	"bruge" vblex pp
	"bruge" adj pp ut sg ind
	"bruge" adj pp nt sg ind
"<på>"
	"på" pr SELECT:4112:2642
;	"på" adv SELECT:4112:2642
"<graven>"
	"grav" n ut sg def nom
	"grave" n ut sg def nom
"<.>"
	"." sent

"<En>"
	"en" det ind ut sg
	"en" num sg ut
;	"en" det qnt ut sg REMOVE:8533:10028
;	"ene" vblex imp REMOVE:8615:4036
"<udbredt>"
	"udbrede" vblex pp
	"udbrede" adj pp ut sg ind
;	"udbrede" adj pp nt sg ind REMOVE:6037:2291
"<skik>"
	"skik" n ut sg ind nom
"<var>"
	"være" vbser past actv
;	"vare" vblex imp REMOVE:6544:2117
"<kremering>"
	"*kremering"
"<,>"
	"," cm
	"," cm clb
"<men>"
	"men" cnjcoo SELECT:998:3443
;	"mene" vblex imp SELECT:998:3443
;	"men" n nt sg ind nom SELECT:998:3443
;	"men" n nt pl ind nom SELECT:998:3443
"<jordfæstning>"
	"jord" n ut sg ind nom cmp
		"fæstning" n ut sg ind nom
"<var>"
	"være" vbser past actv
;	"vare" vblex imp REMOVE:6544:2117
"<også>"
	"også" adv
"<almindelig>"
	"almindelig" adj sint pst ut sg ind
"<.>"
	"." sent

"<Mange steder>"
	"mange steder" adv
"<har>"
	"have" vbhaver pres actv
"<arkæologer>"
	"arkæolog" n ut pl ind nom
"<fundet>"
	"finde" vblex pp SELECT:5782:2410
;	"fund" n nt sg def nom SELECT:5782:2410
;	"finde" adj pp ut sg ind SELECT:5782:2410
;	"finde" adj pp nt sg ind SELECT:5782:2410
"<spor>"
	"spor" n nt pl ind nom
	"spor" n nt sg ind nom
;	"spore" vblex imp REMOVE:6544:2117
"<efter>"
	"efter" pr SELECT:4112:2642
;	"efter" cnjadv SELECT:4112:2642
"<begravelser>"
	"begravelse" n ut pl ind nom
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<skibssætninger>"
	"skib" n nt sg ind nom cmp
		"sætning" n ut pl ind nom
"<,>"
	"," cm
	"," cm clb
"<skibsformede>"
	"skib" n nt sg ind nom cmp
		"for" n nt sg ind nom cmp
			"mede" n ut sg ind nom
"<stensætninger>"
	"stensætning" n ut pl ind nom
"<.>"
	"." sent

"<Skibet>"
	"skibe" vblex pp
	"skib" n nt sg def nom
;	"skibe" adj pp ut sg ind REMOVE:6128:2283
;	"skibe" adj pp nt sg ind REMOVE:6128:2283
"<forekom>"
	"forekomme" vblex past actv
;	"forekomme" vblex imp REMOVE:6536:2116
"<ofte>"
	"ofte" adv SELECT:5755:2849
;	"ofte" adj sint pst ut sg ind SELECT:5755:2849
;	"ofte" adj sint pst nt sg ind SELECT:5755:2849
;	"ofte" adj sint pst un pl ind SELECT:5755:2849
;	"ofte" adj sint pst un sp def SELECT:5755:2849
"<som>"
	"som" cnjsub
	"som" prn rel un sp nom
"<motiv>"
	"motiv" n nt sg ind nom
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<religiøse>"
	"religiøs" adj sint pst un pl ind SELECT:2446:3055
;	"religiøs" adj sint pst un sp def SELECT:2446:3055
"<sammenhænge>"
	"sammenhæng" n ut pl ind nom
"<,>"
	"," cm
	"," cm clb
"<lige>"
	"lige" adv
	"lige" n ut sg ind nom
	"lige" adj sint pst un sp def
	"lig" adj sint pst un pl ind
	"lig" adj sint pst un sp def
	"lige" adj sint pst ut sg ind
	"lige" adj sint pst un pl ind
;	"lig" adj sint pst un sg def REMOVE:5900:2310
;	"lige" adj sint pst nt sg ind REMOVE:6023:2294
"<fra>"
	"fra" pr SELECT:4112:2642
;	"fra" adv SELECT:4112:2642
;	"fra" cnjadv SELECT:4112:2642
;	"fra" abbr SELECT:4112:2642
"<bronzealderens>"
	"bronzealder" n ut sg def gen
"<rageknive>"
	"*rageknive"
"<til>"
	"til" adv
	"til" pr
	"til" cnjsub
	"til" cnjadv
"<vikingetidens>"
	"*vikingetidens"
"<billedsten>"
	"billede" n nt sg ind nom cmp
		"sten" n ut sg ind nom
	"billede" n nt sg ind nom cmp
		"sten" n ut pl ind nom
"<og>"
	"og" adv
	"og" cnjcoo
"<grave>"
	"grave" adv
	"grave" n ut sg ind nom
	"grav" n ut pl ind nom
;	"grave" vblex inf actv REMOVE:7489:1910
"<..>"
	".." sent


"<Vores>"
	"vores" det pos un sp
"<viden>"
	"viden" adv
"<om>"
	"om" pr SELECT:4213:2651
;	"om" cnjsub SELECT:4213:2651
;	"om" cnjadv SELECT:4213:2651
"<gravskikke>"
	"grav" n ut sg ind nom cmp
		"skik" n ut pl ind nom
"<,>"
	"," cm
	"," cm clb
"<forestillinger>"
	"forestilling" n ut pl ind nom
"<og>"
	"og" adv
	"og" cnjcoo
"<ritualer>"
	"ritual" n nt pl ind nom
"<er>"
	"være" vbser pres actv
"<størst>"
	"stor" adj sint sup un sp ind
"<for>"
	"for" adv SELECT:759:3652
;	"for" pr SELECT:759:3652
;	"for" cnjsub SELECT:759:3652
;	"fore" vblex imp SELECT:759:3652
;	"fare" vblex past actv SELECT:759:3652
;	"for" n nt sg ind nom SELECT:759:3652
;	"for" n nt pl ind nom SELECT:759:3652
;	"fare" adj pp ut sg ind SELECT:759:3652
;	"fare" adj pp nt sg ind SELECT:759:3652
"<Vikingetiden>"
	"*Vikingetiden"
"<.>"
	"." sent

"<Nogle>"
	"nogen" det qnt un pl
	"nogen" prn ind un pl
"<af>"
	"af" pr
"<de>"
	"de" prn p3 un pl nom
	"den" det dem un pl
;	"de" np al sg nom REMOVE:7832:de-np
"<mest>"
	"mest" preadv
	"meget" adj sint sup un sp ind
"<fremtrædende>"
	"fremtræde" adj pprs
	"fremtrædende" adj sint pst ut sg ind
	"fremtrædende" adj sint pst nt sg ind
	"fremtrædende" adj sint pst un sp def
;	"fremtrædende" adj sint pst un pl ind REMOVE:6001:2299
"<begravelsespladser>"
	"begravelse" n ut sg ind nom cmp
		"plads" n ut pl ind nom
"<fra>"
	"fra" adv
	"fra" pr
	"fra" cnjadv
	"fra" abbr
"<før>"
	"før" pr SELECT:4074:2639
;	"før" adv REMOVE:1586:3608
;	"føre" vblex imp REMOVE:6544:2117
;	"før" n nt sg ind nom SELECT:4074:2639
;	"før" cnjsub SELECT:4074:2639
;	"før" cnjadv SELECT:4074:2639
-
"<kristen>"
	"kristen" adj sint pst ut sg ind
"<tid>"
	"tid" n ut sg ind nom
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<Skandinavien>"
	"*Skandinavien"
"<findes på>"
	"finde# på" vblex pres pasv
;	"finde# på" vblex inf pasv REMOVE:7512:1912
"<Lindholm>"
	"lind" n ut sg ind nom cmp
		"holm" n ut sg ind nom
"<Høje>"
	"høj" n ut pl ind nom
	"høj" adj sint pst un pl ind
	"høj" adj sint pst un sp def
"<og>"
	"og" adv
	"og" cnjcoo
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<Jelling>"
	"Jelling" np cog nom
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<Danmark>"
	"Danmark" np top nom
"<,>"
	"," cm
	"," cm clb
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<Borre>"
	"Borre" np top nom
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<Norge>"
	"Norge" np top nom
"<og>"
	"og" adv
	"og" cnjcoo
"<Vendel>"
	"ven" n ut sg ind nom cmp
		"del" n ut sg ind nom
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<Sverige>"
	"Sverige" np top nom
"<..>"
	".." sent


"<Der>"
	"der" prn rel un sp nom
	"der" pr
	"der" cnjsub
;	"der" adv REMOVE:6788:10006
"<er>"
	"være" vbser pres actv
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<Norden>"
	"nord" n ut sg def nom
;	"norden" n ut sg ind nom REMOVE:6968:2033
;	"norden" n nt sg ind nom REMOVE:6968:2033
"<kun>"
	"kun" adv SELECT:3541:2865
;	"kunne" vbmod imp SELECT:3541:2865
"<fundet>"
	"finde" vblex pp SELECT:5782:2410
;	"fund" n nt sg def nom SELECT:5782:2410
;	"finde" adj pp ut sg ind SELECT:5782:2410
;	"finde" adj pp nt sg ind SELECT:5782:2410
"<rester>"
	"rest" n ut pl ind nom
;	"restere" vblex imp REMOVE:6544:2117
"<efter>"
	"efter" pr SELECT:4112:2642
;	"efter" cnjadv SELECT:4112:2642
"<mennesker>"
	"menneske" n nt pl ind nom
"<fra>"
	"fra" adv
	"fra" pr
	"fra" cnjadv
	"fra" abbr
"<den>"
	"den" det dem ut sg
;	"den" prn p3 ut sg nom REMOVE:6636:2083
;	"den" prn p3 ut sg acc REMOVE:6636:2083
"<sene>"
	"sen" adj sint pst un sp def
;	"sene" n ut sg ind nom REMOVE:7062:2008
;	"sen" adj sint pst un pl ind REMOVE:6001:2299
"<del>"
	"del" n ut sg ind nom
;	"dele" vblex imp REMOVE:6544:2117
"<af>"
	"af" pr
"<jægerstenalderen>"
	"jæger" n ut sg ind nom cmp
		"stenalder" n ut sg def nom
"<for>"
	"for" pr SELECT:772:3634
;	"for" adv REMOVE:1573:3631
;	"fore" vblex imp REMOVE:1578:3626
;	"fare" vblex past actv REMOVE:1578:3626
;	"for" n nt pl ind nom REMOVE:1728:10011
;	"for" n nt sg ind nom REMOVE:1728:10011
;	"fare" adj pp nt sg ind SELECT:772:3634
;	"for" cnjsub SELECT:772:3634
;	"fare" adj pp ut sg ind SELECT:772:3634
"<ca.>"
	"ca." adv
	"ca." abbr
	"ca." n nom
"<9.000>"
	"9.000" det qnt pl
"<år>"
	"år" n nt sg ind nom
	"år" n nt pl ind nom
"<siden>"
	"siden" adv SELECT:1228:3304
;	"side" n ut sg def nom REMOVE:1887:3298
;	"siden" pr SELECT:1228:3304
;	"siden" cnjsub SELECT:1228:3304
;	"siden" cnjadv SELECT:1228:3304
"<.>"
	"." sent

"<Levn>"
	"levn" n nt pl ind nom
	"levn" n nt sg ind nom
;	"levne" vblex imp REMOVE:6524:2114
"<fra>"
	"fra" adv
	"fra" pr
	"fra" cnjadv
	"fra" abbr
"<denne>"
	"denne" det dem ut sg
	"denne" prn dem ut sg nom
"<periode>"
	"periode" n ut sg ind nom
"<viser>"
	"vise" vblex pres actv SELECT:5348:2462
;	"vise" n ut pl ind nom SELECT:5348:2462
"<,>"
	"," cm
	"," cm clb
"<at>"
	"at" cnjsub SELECT:8063:1756
;	"at" part SELECT:8063:1756
;	"at" adv SELECT:8063:1756
"<der>"
	"der" adv SELECT:3356:2846
;	"der" pr SELECT:3356:2846
;	"der" cnjsub SELECT:3356:2846
;	"der" prn rel un sp nom SELECT:3356:2846
"<var>"
	"være" vbser past actv
;	"vare" vblex imp REMOVE:6529:2115
"<mange>"
	"mange" det qnt un pl SELECT:3655:2784
;	"mange" prn ind un pl nom SELECT:3655:2784
;	"mange" adj sint pst un pl ind SELECT:3655:2784
"<forskellige>"
	"forskellig" adj sint pst un pl ind SELECT:2483:3057
;	"forskellige" adv SELECT:2483:3057
;	"forskellig" adj sint pst un sp def SELECT:2483:3057
"<begravelser>"
	"begravelse" n ut pl ind nom
"<:>"
	":" sent

"<Der>"
	"der" adv SELECT:3365:2848
;	"der" pr SELECT:3365:2848
;	"der" cnjsub SELECT:3365:2848
;	"der" prn rel un sp nom SELECT:3365:2848
"<kendes>"
	"kende" vblex pres pasv SELECT:5439:2471
;	"kende" vblex inf pasv SELECT:5439:2471
;	"kende" n ut sg ind gen SELECT:5439:2471
"<grave>"
	"grave" adv
	"grave" n ut sg ind nom
	"grav" n ut pl ind nom
;	"grave" vblex inf actv REMOVE:7512:1912
"<med>"
	"med" pr SELECT:4112:2642
;	"med" adv SELECT:4112:2642
"<både>"
	"både" cnjcoo
	"båd" n ut pl ind nom
"<brændte>"
	"brænde" adj pp pl
	"brænde" vblex past actv
;	"brænde" adj pp sg def REMOVE:8380:1725
"<og>"
	"og" adv
	"og" cnjcoo
"<ikke>"
	"ikke" adv
-
"<brændte>"
	"brænde" vblex past actv
;	"brænde" adj pp sg def REMOVE:5848:2322
;	"brænde" adj pp pl REMOVE:7682:1895
"<knogler>"
	"knogle" n ut pl ind nom
"<på>"
	"på" pr SELECT:4112:2642
;	"på" adv SELECT:4112:2642
"<de>"
	"de" prn p3 un pl nom
	"den" det dem un pl
;	"de" np al sg nom REMOVE:7832:de-np
"<samme>"
	"samme" det dem ut sp
	"samme" det dem nt sp
	"samme" prn def un sg nom
"<begravelsespladser>"
	"begravelse" n ut sg ind nom cmp
		"plads" n ut pl ind nom
"<.>"
	"." sent

"<Nogle>"
	"nogen" det qnt un pl
	"nogen" prn ind un pl
"<fik>"
	"få" vblex past actv
"<gaver>"
	"gav" n ut pl ind nom
	"gave" n ut pl ind nom
"<med>"
	"med" adv
	"med" pr
"<sig>"
	"sig" prn ref p3 un sp SELECT:4434:2607
;	"sige" vblex imp SELECT:4434:2607
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<graven>"
	"grav" n ut sg def nom
	"grave" n ut sg def nom
"<,>"
	"," cm
	"," cm clb
"<andre>"
	"anden" det un pl
	"anden" prn ind un pl nom
;	"anden" adj sint pst un pl REMOVE:8593:4030
;	"anden" adj ord pst un pl ind REMOVE:8593:4030
"<ikke>"
	"ikke" adv
"<.>"
	"." sent

"<Der>"
	"der" adv SELECT:3365:2848
;	"der" pr SELECT:3365:2848
;	"der" cnjsub SELECT:3365:2848
;	"der" prn rel un sp nom SELECT:3365:2848
"<er>"
	"være" vbser pres actv
"<også>"
	"også" adv
"<konstateret>"
	"konstatere" vblex pp
;	"konstatere" adj pp ut sg ind REMOVE:5848:2322
;	"konstatere" adj pp nt sg ind REMOVE:5848:2322
"<rester>"
	"rest" n ut pl ind nom
;	"restere" vblex imp REMOVE:6544:2117
"<af>"
	"af" pr
"<menneskeknogler>"
	"menneske" n nt sg ind nom cmp
		"knogle" n ut pl ind nom
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<køkkenmøddinger>"
	"*køkkenmøddinger"
"<.>"
	"." sent

"<De>"
	"de" prn p3 un pl nom
	"De" prn p2 un pl nom
	"den" det dem un pl
;	"de" np al sg nom REMOVE:7835:de-np
"<døde>"
	"død" adj sint pst un pl ind
	"død" n ut pl ind nom
	"død" adj sint pst un sp def
;	"dø" adj pp sg def REMOVE:5875:2307
;	"dø" vblex past actv REMOVE:7783:1831
;	"dø" adj pp pl REMOVE:7682:1895
"<blev>"
	"blive" vblex past actv
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<jægerstenalderen>"
	"jæger" n ut sg ind nom cmp
		"stenalder" n ut sg def nom
"<begravet>"
	"begrave" vblex pp SELECT:5782:2410
;	"begrave" adj pp ut sg ind SELECT:5782:2410
;	"begrave" adj pp nt sg ind SELECT:5782:2410
"<tæt på>"
	"tæt på" adv
"<de>"
	"den" det dem un pl SELECT:3586:2777
;	"de" np al sg nom SELECT:3586:2777
;	"de" prn p3 un pl nom SELECT:3586:2777
"<levende>"
	"levende" adj sint pst un pl ind SELECT:5831:3044
;	"leve" adj pprs SELECT:5831:3044
;	"levende" adj sint pst ut sg ind SELECT:5831:3044
;	"levende" adj sint pst nt sg ind SELECT:5831:3044
;	"levende" adj sint pst un sp def SELECT:5831:3044
"<gerne>"
	"gerne" adv
"<på>"
	"på" adv
	"på" pr
"<selve>"
	"selv" det emph def
	"selv" prn ref un pl nom
"<bopladsen>"
	"boplads" n ut sg def nom
"<.>"
	"." sent

"<Der>"
	"der" adv SELECT:3365:2848
;	"der" pr SELECT:3365:2848
;	"der" cnjsub SELECT:3365:2848
;	"der" prn rel un sp nom SELECT:3365:2848
"<er>"
	"være" vbser pres actv
"<udgravet>"
	"udgravet" adj sint pst ut sg ind
	"udgravet" adj sint pst nt sg ind
"<et>"
	"en" det ind nt sg SELECT:3871:2739
;	"et" num sg nt REMOVE:1702:10027
;	"en" det qnt nt sg SELECT:3871:2739
"<spædbarn>"
	"spædbarn" n nt sg ind nom
"<,>"
	"," cm
	"," cm clb
"<som>"
	"som" cnjsub SELECT:1300:3252
;	"som" prn rel un sp nom SELECT:1300:3252
"<var>"
	"være" vbser past actv
;	"vare" vblex imp REMOVE:6524:2114
"<lagt>"
	"lægge" vblex pp SELECT:5664:2406
;	"lægge" adj pp ut sg ind SELECT:5664:2406
;	"lægge" adj pp nt sg ind SELECT:5664:2406
;	"ligge" adj pp ut sg ind SELECT:5664:2406
;	"ligge" adj pp nt sg ind SELECT:5664:2406
"<på>"
	"på" pr
;	"på" adv REMOVE:6327:2225
"<et>"
	"en" det ind nt sg SELECT:3871:2739
;	"et" num sg nt REMOVE:1702:10027
;	"en" det qnt nt sg SELECT:3871:2739
"<træfad>"
	"træ" n nt sg ind nom cmp
		"fad" n nt sg ind nom
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<en>"
	"en" det ind ut sg
;	"en" num sg ut REMOVE:1694:10025
;	"ene" vblex imp REMOVE:6524:2114
;	"en" det qnt ut sg REMOVE:8533:10028
"<åben>"
	"åben" adj sint pst ut sg ind
"<begravelse>"
	"begravelse" n ut sg ind nom
"<,>"
	"," cm
	"," cm clb
"<så>"
	"så" cnjsub SELECT:8063:1756
;	"så" vblex imp REMOVE:6524:2114
;	"så" vblex inf actv REMOVE:7472:1908
;	"så" adv SELECT:8063:1756
;	"se" vblex past actv SELECT:8063:1756
"<alle>"
	"al" det qnt pl
	"al" prn def un pl nom
;	"alle" n ut sg ind nom REMOVE:1468:3781
"<kunne>"
	"kunne" vbmod inf actv
	"kunne" vbmod past actv
"<kigge>"
	"kigge" vblex inf actv
"<lige>"
	"lige" adv
	"lige" n ut sg ind nom
	"lige" adj sint pst un sp def
	"lig" adj sint pst un pl ind
	"lig" adj sint pst un sp def
	"lige" adj sint pst ut sg ind
	"lige" adj sint pst un pl ind
;	"lig" adj sint pst un sg def REMOVE:5900:2310
;	"lige" adj sint pst nt sg ind REMOVE:6023:2294
"<ned>"
	"ned" adv
	"ned" pr
"<på>"
	"på" adv
	"på" pr
"<det>"
	"den" det dem nt sg
	"det" prn p3 nt sg nom
	"det" prn p3 nt sg acc
"<..>"
	".." sent


"<Kort>"
	"kort" adv
	"kort" adj sint pst ut sg ind
;	"kort" adj sint pst nt sg ind REMOVE:6023:2294
;	"kort" n nt sg ind nom REMOVE:8687:4099
;	"kort" n nt pl ind nom REMOVE:8687:4099
"<efter>"
	"efter" pr
	"efter" cnjadv
"<den>"
	"den" det dem ut sg
	"den" prn p3 ut sg nom
	"den" prn p3 ut sg acc
"<neolitiske>"
	"*neolitiske"
"<revolution>"
	"revolution" n ut sg ind nom
"<begyndte>"
	"begynde" adj pp sg def
	"begynde" vblex past actv
;	"begynde" adj pp pl REMOVE:6001:2299
"<opførelsen>"
	"opførelse" n ut sg def nom
"<monumentale>"
	"*monumentale"
"<gravhøje>"
	"gravhøj" n ut pl ind nom
"<,>"
	"," cm
	"," cm clb
"<en>"
	"en" det ind ut sg
;	"en" num sg ut REMOVE:1694:10025
;	"ene" vblex imp REMOVE:6524:2114
;	"en" det qnt ut sg REMOVE:8533:10028
"<gravform>"
	"grav" n ut sg ind nom cmp
		"form" n ut sg ind nom
"<der>"
	"der" prn rel un sp nom SELECT:3337:10013
;	"der" adv SELECT:3337:10013
;	"der" pr SELECT:3337:10013
;	"der" cnjsub SELECT:3337:10013
"<blev>"
	"blive" vblex past actv
"<benyttet>"
	"benytte" vblex pp SELECT:5664:2406
;	"benytte" adj pp ut sg ind SELECT:5664:2406
;	"benytte" adj pp nt sg ind SELECT:5664:2406
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<årtusinder>"
	"årtusind" n nt pl ind nom
"<helt frem>"
	"helt frem" pr
"<til>"
	"til" pr SELECT:4239:2653
;	"til" adv SELECT:4239:2653
;	"til" cnjsub SELECT:4239:2653
;	"til" cnjadv SELECT:4239:2653
"<vikingetiden>"
	"*vikingetiden"
"<.>"
	"." sent

"<I>"
	"i" pr SELECT:4074:2639
;	"I" np top nom SELECT:4074:2639
;	"I" prn p2 un pl nom SELECT:4074:2639
;	"ialphabet" n nt sg ind nom SELECT:4074:2639
"<forbindelse>"
	"forbindelse" n ut sg ind nom
"<med>"
	"med" pr SELECT:4112:2642
;	"med" adv SELECT:4112:2642
"<højene>"
	"høj" n ut pl def nom
"<blev>"
	"blive" vblex past actv
"<der>"
	"der" pr SELECT:4147:2645
;	"der" adv SELECT:4147:2645
;	"der" cnjsub SELECT:4147:2645
;	"der" prn rel un sp nom SELECT:4147:2645
"<opført>"
	"opføre" vblex pp
	"opføre" adj pp ut sg ind
	"opføre" adj pp nt sg ind
"<store>"
	"stor" adj sint pst un pl ind SELECT:2446:3055
;	"stor" adj sint pst un sp def SELECT:2446:3055
"<indhegninger>"
	"indhegning" n ut pl ind nom
"<,>"
	"," cm
	"," cm clb
"<som>"
	"som" cnjsub SELECT:1300:3252
;	"som" prn rel un sp nom SELECT:1300:3252
"<sandsynligvis>"
	"sandsynligvis" adv
"<blev>"
	"blive" vblex past actv
"<brugt>"
	"bruge" vblex pp SELECT:5664:2406
;	"bruge" adj pp ut sg ind SELECT:5664:2406
;	"bruge" adj pp nt sg ind SELECT:5664:2406
"<til>"
	"til" pr SELECT:4239:2653
;	"til" adv SELECT:4239:2653
;	"til" cnjsub SELECT:4239:2653
;	"til" cnjadv SELECT:4239:2653
"<ritualer>"
	"ritual" n nt pl ind nom
"<med>"
	"med" pr SELECT:4112:2642
;	"med" adv SELECT:4112:2642
"<betydning>"
	"betydning" n ut sg ind nom
"<for>"
	"fare" adj pp nt sg ind
	"for" pr
	"for" cnjsub
	"fare" adj pp ut sg ind
;	"for" adv REMOVE:1573:3631
;	"fore" vblex imp REMOVE:1578:3626
;	"fare" vblex past actv REMOVE:1578:3626
;	"for" n nt pl ind nom REMOVE:1728:10011
;	"for" n nt sg ind nom REMOVE:1728:10011
"<hele>"
	"hel" adj sint pst un sp def
;	"hele" n ut sg ind nom REMOVE:1642:3560
;	"hele" n ut pl ind nom REMOVE:1642:3560
;	"hele" n nt sg ind nom REMOVE:1642:3560
;	"hele" n nt pl ind nom REMOVE:1642:3560
;	"hel" adj sint pst un pl ind REMOVE:6001:2299
;	"hele" vblex inf actv REMOVE:8619:4037
"<samfundet>"
	"samfund" n nt sg def nom
"<.>"
	"." sent

"<Det>"
	"den" det dem nt sg
;	"det" prn p3 nt sg nom REMOVE:6421:2125
;	"det" prn p3 nt sg acc REMOVE:6421:2125
"<krævede>"
	"kræve" vblex past actv
;	"kræve" adj pp pl REMOVE:6001:2299
;	"kræve" adj pp sg def REMOVE:7682:1895
"<stor>"
	"stor" adj sint pst ut sg ind
"<ingeniørkunnen>"
	"*ingeniørkunnen"
"<og>"
	"og" adv
	"og" cnjcoo
"<en>"
	"en" det ind ut sg
;	"en" num sg ut REMOVE:1694:10025
;	"ene" vblex imp REMOVE:6544:2117
;	"en" det qnt ut sg REMOVE:8533:10028
"<betydelig>"
	"betydelig" adj sint pst ut sg ind
"<arbejdsstyrke>"
	"arbejdsstyrke" n ut sg ind nom
"<.>"
	"." sent

"<Det>"
	"det" prn p3 nt sg nom SELECT:4434:2607
	"det" prn p3 nt sg acc SELECT:4434:2607
;	"den" det dem nt sg SELECT:4434:2607
"<vidner>"
	"vidne" vblex pres actv SELECT:5393:2467
;	"vidne" n nt pl ind nom SELECT:5393:2467
"<om>"
	"om" pr
	"om" cnjsub
	"om" cnjadv
"<et>"
	"en" det ind nt sg SELECT:3871:2739
;	"et" num sg nt REMOVE:1702:10027
;	"en" det qnt nt sg SELECT:3871:2739
"<velorganiseret>"
	"*velorganiseret"
"<samfund>"
	"samfund" n nt pl ind nom
;	"samfund" n nt sg ind nom REMOVE:8720:et-bid
"<.>"
	"." sent

"<De>"
	"den" det dem un pl SELECT:3641:2783
;	"de" np al sg nom REMOVE:7835:de-np
;	"de" prn p3 un pl nom SELECT:3641:2783
;	"De" prn p2 un pl nom SELECT:3641:2783
"<døde>"
	"død" adj sint pst un pl ind SELECT:2483:3057
;	"dø" adj pp sg def REMOVE:5848:2322
;	"dø" vblex past actv REMOVE:7810:1835
;	"død" n ut pl ind nom REMOVE:8691:6201
;	"død" adj sint pst un sp def SELECT:2483:3057
;	"dø" adj pp pl SELECT:2483:3057 REMOVE:7682:1895
"<slægtninge>"
	"slægtning" n ut pl ind nom
"<havde>"
	"have" vbhaver past actv
"<betydning>"
	"betydning" n ut sg ind nom
"<,>"
	"," cm
	"," cm clb
"<fordi>"
	"fordi" cnjsub SELECT:8063:1756
;	"fordi" cnjadv SELECT:8063:1756
"<gravpladserne>"
	"gravplads" n ut pl def nom
"<tydeligvis>"
	"tydeligvis" adv
"<fungerede>"
	"fungere" vblex past actv
;	"fungere" adj pp pl REMOVE:6063:2274
;	"fungere" adj pp sg def REMOVE:6063:2274
"<som>"
	"som" cnjsub
	"som" prn rel un sp nom
"<samlingssted>"
	"samlingssted" n nt sg ind nom
"<.>"
	"." sent

"<De>"
	"den" det dem un pl SELECT:3641:2783
;	"de" np al sg nom REMOVE:7835:de-np
;	"de" prn p3 un pl nom SELECT:3641:2783
;	"De" prn p2 un pl nom SELECT:3641:2783
"<ældste>"
	"gammel" adj sint sup un sp def
;	"ældste" n ut sg ind nom REMOVE:8691:6201
;	"ældste" n ut pl ind nom REMOVE:8691:6201
"<gravhøje>"
	"gravhøj" n ut pl ind nom
"<var>"
	"være" vbser past actv
;	"vare" vblex imp REMOVE:6544:2117
"<langhøje>"
	"*langhøje"
"<og>"
	"og" adv
	"og" cnjcoo
"<havde>"
	"have" vbhaver past actv
"<gravkamre>"
	"gravkammer" n nt pl ind nom
"<af>"
	"af" pr
"<træ>"
	"træ" n nt sg ind nom
"<.>"
	"." sent

"<De>"
	"De" prn p2 un pl nom SELECT:4434:2607
	"de" prn p3 un pl nom SELECT:4434:2607
;	"de" np al sg nom SELECT:4434:2607
;	"den" det dem un pl SELECT:4434:2607
"<lignede>"
	"ligne" vblex past actv
;	"ligne" adj pp sg def REMOVE:5875:2307
;	"ligne" adj pp pl REMOVE:6052:2273
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<form>"
	"form" n ut sg ind nom
;	"forme" vblex imp REMOVE:6529:2115
"<og>"
	"og" adv
	"og" cnjcoo
"<størrelse>"
	"størrelse" n ut sg ind nom
"<de>"
	"de" prn p3 un pl nom
	"den" det dem un pl
;	"de" np al sg nom REMOVE:7832:de-np
"<langstrakte>"
	"*langstrakte"
"<beboelseshuse>"
	"beboelse" n ut sg ind nom cmp
		"hus" n nt pl ind nom
"<.>"
	"." sent

"<Gravhøjen>"
	"gravhøj" n ut sg def nom
"<blev>"
	"blive" vblex past actv
"<formentligt>"
	"*formentligt"
"<opfattet>"
	"opfatte" vblex pp SELECT:5782:2410
;	"opfatte" adj pp ut sg ind SELECT:5782:2410
;	"opfatte" adj pp nt sg ind SELECT:5782:2410
"<som>"
	"som" cnjsub
;	"som" prn rel un sp nom REMOVE:6683:2073
"<de>"
	"de" prn p3 un pl nom
	"den" det dem un pl
;	"de" np al sg nom REMOVE:7832:de-np
"<dødes>"
	"dø" vblex past pasv
	"død" n ut pl ind gen
"<bolig>"
	"bolig" n ut sg ind nom
"<.>"
	"." sent

"<Omkring>"
	"omkring" adv
	"omkring" pr
"<3500>"
	"3500" det qnt pl
-
"<3200>"
	"3200" det qnt pl
"<f.>"
	"f." abbr
"<Kr.>"
	"kr." abbr
	"kr." n nom
"<blev>"
	"blive" vblex past actv
"<gravkamrenes>"
	"gravkammer" n nt pl def gen
"<trævægge>"
	"træ" n nt sg ind nom cmp
		"væg" n ut pl ind nom
"<erstattet>"
	"erstatte" vblex pp SELECT:5642:2403
;	"erstatte" adj pp ut sg ind SELECT:5642:2403
;	"erstatte" adj pp nt sg ind SELECT:5642:2403
"<af>"
	"af" pr
"<store>"
	"stor" adj sint pst un sp def
;	"stor" adj sint pst un pl ind REMOVE:6001:2299
"<stenblokke>"
	"sten" n ut sg ind nom cmp
		"blok" n ut pl ind nom
"<,>"
	"," cm
	"," cm clb
"<de>"
	"den" det dem un pl SELECT:3586:2777
;	"de" np al sg nom SELECT:3586:2777
;	"de" prn p3 un pl nom SELECT:3586:2777
"<såkaldte>"
	"såkaldt" adj sint pst un pl ind SELECT:5831:3044
;	"såkaldt" adj sint pst un sp def SELECT:5831:3044
"<stendysser>"
	"*stendysser"
"<.>"
	"." sent

"<I>"
	"i" pr SELECT:1183:10005
;	"I" np top nom SELECT:1183:10005
;	"I" prn p2 un pl nom SELECT:1183:10005
;	"ialphabet" n nt sg ind nom SELECT:1183:10005
"<de>"
	"den" det dem un pl
;	"de" prn p3 un pl nom REMOVE:6623:2082
;	"de" np al sg nom REMOVE:7832:de-np
"<ældste>"
	"gammel" adj sint sup un sp def
;	"ældste" n ut sg ind nom REMOVE:8691:6201
;	"ældste" n ut pl ind nom REMOVE:8691:6201
"<høje>"
	"høj" n ut pl ind nom
	"høj" adj sint pst un pl ind
	"høj" adj sint pst un sp def
"<var>"
	"være" vbser past actv
;	"vare" vblex imp REMOVE:6524:2114
"<der>"
	"der" prn rel un sp nom
	"der" pr
	"der" cnjsub
;	"der" adv REMOVE:6797:10011
"<kun>"
	"kun" adv
;	"kunne" vbmod imp REMOVE:6524:2114
"<plads>"
	"plads" n ut sg ind nom
"<til>"
	"til" adv
	"til" pr
	"til" cnjsub
	"til" cnjadv
"<få>"
	"få" vblex inf actv SELECT:1094:10026
;	"få" adj sint pst ut sg ind SELECT:1094:10026
;	"få" adj sint pst nt sg ind SELECT:1094:10026
;	"få" adj sint pst un pl ind SELECT:1094:10026
;	"få" adj sint pst un sp def SELECT:1094:10026
;	"få" vblex imp SELECT:1094:10026 REMOVE:6508:2108
"<lig>"
	"lig" adj sint pst un sg ind
	"lig" n nt sg ind nom
	"lig" n nt pl ind nom
	"lig" adj sint pst ut sg ind
	"lig" adj sint pst nt sg ind
;	"ligge" vblex imp REMOVE:6524:2114
"<,>"
	"," cm
	"," cm clb
"<men>"
	"men" cnjcoo SELECT:998:3443
;	"mene" vblex imp SELECT:998:3443
;	"men" n nt sg ind nom SELECT:998:3443
;	"men" n nt pl ind nom SELECT:998:3443
"<senere>"
	"senere" adv
	"sen" adj sint comp un sp
"<blev>"
	"blive" vblex past actv
"<flere>"
	"flere" det qnt un pl
	"mange" adj sint comp un sp
"<begravet>"
	"begrave" vblex pp
	"begrave" adj pp ut sg ind
;	"begrave" adj pp nt sg ind REMOVE:6010:2295
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<samme>"
	"samme" det dem ut sp
	"samme" det dem nt sp
	"samme" prn def un sg nom
"<kammer>"
	"kamme" vblex pres actv
	"kammer" n nt sg ind nom
"<.>"
	"." sent

"<De>"
	"de" prn p3 un pl nom
	"De" prn p2 un pl nom
	"den" det dem un pl
;	"de" np al sg nom REMOVE:7835:de-np
"<døde>"
	"død" adj sint pst un pl ind
	"død" n ut pl ind nom
	"død" adj sint pst un sp def
;	"dø" adj pp sg def REMOVE:5875:2307
;	"dø" vblex past actv REMOVE:7783:1831
;	"dø" adj pp pl REMOVE:7682:1895
"<fik>"
	"få" vblex past actv
"<som>"
	"som" cnjsub
	"som" prn rel un sp nom
"<regel>"
	"regel" n ut sg ind nom
"<personlige>"
	"personlig" adj sint pst un pl ind
	"personlig" adj sint pst un sp def
"<ejendele>"
	"*ejendele"
"<med>"
	"med" adv
	"med" pr
"<som>"
	"som" cnjsub
	"som" prn rel un sp nom
"<gravgods>"
	"grav" n ut sg ind nom cmp
		"gods" n nt sg ind nom
 – 
"<og>"
	"og" adv
	"og" cnjcoo
"<lerkar>"
	"ler" n ut sg ind nom cmp
		"kar" n nt sg ind nom
	"ler" n ut sg ind nom cmp
		"kar" n nt pl ind nom
	"ler" n nt sg ind nom cmp
		"kar" n nt sg ind nom
	"ler" n nt sg ind nom cmp
		"kar" n nt pl ind nom
"<med>"
	"med" pr SELECT:4112:2642
;	"med" adv SELECT:4112:2642
"<mad>"
	"mad" n ut sg ind nom
;	"made" vblex imp REMOVE:6529:2115
"<og>"
	"og" adv
	"og" cnjcoo
"<drikke>"
	"drikke" vblex inf actv
	"drik" n ut pl ind nom
	"drikke" n ut sg ind nom
	"drikke" n ut pl ind nom
	"drikke" n nt sg ind nom
"<.>"
	"." sent

"<I>"
	"i" pr SELECT:4074:2639
;	"I" np top nom SELECT:4074:2639
;	"I" prn p2 un pl nom SELECT:4074:2639
;	"ialphabet" n nt sg ind nom SELECT:4074:2639
"<perioden>"
	"periode" n ut sg def nom
"<3250>"
	"3250" det qnt pl
-
"<3100>"
	"3100" det qnt pl
"<f>"
	"falphabet" n nt sg ind nom
"<.>"
	"." sent

"<Kr.>"
	"kr." abbr
	"kr." n nom
"<byggedes>"
	"bygge" vblex past pasv
"<de>"
	"de" prn p3 un pl nom
	"den" det dem un pl
;	"de" np al sg nom REMOVE:7832:de-np
"<større>"
	"stor" adj sint comp un sp
"<jættestuer>"
	"jætte" n ut sg ind nom cmp
		"stue" n ut pl ind nom
"<,>"
	"," cm
	"," cm clb
"<hvor>"
	"hvor" adv
;	"hvor" cnjsub REMOVE:6913:2038
"<der>"
	"der" adv SELECT:3356:2846
;	"der" pr SELECT:3356:2846
;	"der" cnjsub SELECT:3356:2846
;	"der" prn rel un sp nom SELECT:3356:2846
"<var>"
	"være" vbser past actv
;	"vare" vblex imp REMOVE:6529:2115
"<plads>"
	"plads" n ut sg ind nom
"<til>"
	"til" pr SELECT:4239:2653
;	"til" adv SELECT:4239:2653
;	"til" cnjsub SELECT:4239:2653
;	"til" cnjadv SELECT:4239:2653
"<mere>"
	"mere" preadv
	"mere" adv
	"meget" adj sint comp un sp
"<end>"
	"end" pr SELECT:4074:2639
;	"ende" vblex imp REMOVE:6529:2115
;	"end" adv SELECT:4074:2639
;	"end" cnjadv SELECT:4074:2639
;	"end" n ut sg ind nom SELECT:4074:2639
"<100>"
	"100" det qnt pl
"<grave>"
	"grave" n ut sg ind nom
	"grav" n ut pl ind nom
;	"grave" adv REMOVE:6347:2228
;	"grave" vblex inf actv REMOVE:7512:1912
"<.>"
	"." sent

"<De>"
	"de" prn p3 un pl nom
	"De" prn p2 un pl nom
	"den" det dem un pl
;	"de" np al sg nom REMOVE:7835:de-np
"<døde>"
	"død" adj sint pst un pl ind
	"død" n ut pl ind nom
	"død" adj sint pst un sp def
;	"dø" adj pp sg def REMOVE:5875:2307
;	"dø" vblex past actv REMOVE:7783:1831
;	"dø" adj pp pl REMOVE:7682:1895
"<fik>"
	"få" vblex past actv
"<fortsat>"
	"fortsat" adv
	"fortsætte" vblex pp
;	"fortsætte" adj pp ut sg ind REMOVE:5848:2322
;	"fortsætte" adj pp nt sg ind REMOVE:5848:2322
"<gaver>"
	"gav" n ut pl ind nom
	"gave" n ut pl ind nom
"<og>"
	"og" adv
	"og" cnjcoo
"<fødevarer>"
	"fødevare" n ut pl ind nom
"<med>"
	"med" adv
	"med" pr
"<i>"
	"i" pr
;	"ialphabet" n nt sg ind nom REMOVE:1487:10022
"<graven>"
	"grav" n ut sg def nom
	"grave" n ut sg def nom
"<.>"
	"." sent

"<Der>"
	"der" adv SELECT:3365:2848
;	"der" pr SELECT:3365:2848
;	"der" cnjsub SELECT:3365:2848
;	"der" prn rel un sp nom SELECT:3365:2848
"<er>"
	"være" vbser pres actv
"<også>"
	"også" adv
"<blevet>"
	"blive" vblex pp
;	"blive" adj pp ut sg ind REMOVE:8648:4065
;	"blive" adj pp nt sg ind REMOVE:8648:4065
"<fundet>"
	"finde" vblex pp SELECT:5782:2410
;	"fund" n nt sg def nom SELECT:5782:2410
;	"finde" adj pp ut sg ind SELECT:5782:2410
;	"finde" adj pp nt sg ind SELECT:5782:2410
"<grave>"
	"grave" adv
	"grave" n ut sg ind nom
	"grav" n ut pl ind nom
;	"grave" vblex inf actv REMOVE:7512:1912
"<uden>"
	"uden" pr
	"uden" cnjcoo
"<for>"
	"for" pr SELECT:779:10003
;	"for" adv SELECT:779:10003
;	"for" cnjsub SELECT:779:10003
;	"fore" vblex imp SELECT:779:10003
;	"fare" vblex past actv SELECT:779:10003
;	"for" n nt sg ind nom SELECT:779:10003
;	"for" n nt pl ind nom SELECT:779:10003
;	"fare" adj pp ut sg ind SELECT:779:10003
;	"fare" adj pp nt sg ind SELECT:779:10003
"<flere>"
	"flere" det qnt un pl
	"mange" adj sint comp un sp
"<jættestuer>"
	"jætte" n ut sg ind nom cmp
		"stue" n ut pl ind nom
"<med>"
	"med" adv
	"med" pr
"<en>"
	"en" det ind ut sg
;	"en" num sg ut REMOVE:1694:10025
;	"ene" vblex imp REMOVE:6544:2117
;	"en" det qnt ut sg REMOVE:8533:10028
"<mere>"
	"meget" adj sint comp un sp SELECT:3274:2874
;	"mere" preadv SELECT:3274:2874
;	"mere" adv SELECT:3274:2874
"<enkel>"
	"enkel" adj sint pst ut sg ind
"<udformning>"
	"udformning" n ut sg ind nom
"<..>"
	".." sent



